### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by TAKAi3y0** [TAKAi3y0/furima-32117#10]
# URL
https://furima-32117.herokuapp.com/
# basic認証
id : admin
password : 2222
# 出品者用のメールアドレスとパスワード
メールアドレス : xxxxxx@xxxxxx
パスワード : xxx111
# 購入者用のメールアドレスとパスワード
メールアドレス : xxxxxx@xxxxxxx
パスワード : xxx111
# 購入用カードの番号・期限・セキュリティコード
番号 : 4242424242424242
期限(月) : 3
期限(年) : 23
セキュリティコード : 123

**Comment by MasaakiTanabashi** [comment]
高井さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**◎出品者以外が商品の編集ができてしまいます。**
URLに直接入力する（~~/items/〇〇/**edit**）と、出品者以外でも商品の編集ができてしまいます。
トップページへ遷移するように修正しましょう。

修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by TAKAi3y0** [comment]
# 変更点
・move_to_indexの条件文を修正した

**Comment by MasaakiTanabashi** [comment]
高井さん、迅速な対応ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by TAKAi3y0** [comment]
<img width="434" alt="5452944e73711a36c0ae763ea7a41f91" src="https://user-images.githubusercontent.com/73812712/103096405-2f975000-4647-11eb-9a6d-4e96a22d58f8.png">
